# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Which_match', models.CharField(default='abcd', max_length=20)),
                ('Year', models.IntegerField()),
                ('Month', models.CharField(max_length=4)),
                ('Date', models.IntegerField()),
                ('Day', models.CharField(max_length=4)),
                ('Hour', models.IntegerField()),
                ('Minute', models.IntegerField()),
                ('Second', models.IntegerField()),
                ('P_score', models.IntegerField(default=0)),
                ('K_score', models.IntegerField(default=0)),
            ],
        ),
    ]
