# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_quiz_start', models.BooleanField(default=True)),
                ('ment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('right', models.BooleanField(default=False)),
                ('is_postech', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.IntegerField()),
                ('quiz_content', models.CharField(max_length=500)),
                ('quiz_image', models.ImageField(upload_to='images/quiz/')),
                ('option1', models.CharField(max_length=40)),
                ('option2', models.CharField(max_length=40)),
                ('option3', models.CharField(max_length=40)),
                ('option4', models.CharField(max_length=40)),
                ('option5', models.CharField(max_length=40)),
                ('option6', models.CharField(max_length=40)),
                ('option7', models.CharField(max_length=40)),
                ('option8', models.CharField(max_length=40)),
                ('option9', models.CharField(max_length=40)),
                ('option10', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='QuizNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='RightWrong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_postech', models.BooleanField(default=True)),
                ('right_wrong', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('is_postech', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='bingo',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
