# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option10',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option5',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option6',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option7',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option8',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option9',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_image',
            field=models.ImageField(blank=True, upload_to='images/quiz/'),
        ),
    ]
