# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_banneduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='banned_user',
            field=models.TextField(),
        ),
    ]
