# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhichVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_video', models.TextField()),
            ],
        ),
    ]
