# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_whichvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.TextField()),
                ('p_score', models.IntegerField(default=0)),
                ('k_score', models.IntegerField(default=0)),
            ],
        ),
    ]
