# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='Day',
            field=models.CharField(default='abcd', max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='Hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='Minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='Month',
            field=models.CharField(default='abcd', max_length=4),
        ),
        migrations.AddField(
            model_name='match',
            name='Second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='Year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_name',
            field=models.CharField(default='sports', max_length=20),
        ),
    ]
