# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20170916_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Day',
            field=models.CharField(default='Mon', max_length=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='Month',
            field=models.CharField(default='Sep', max_length=4),
        ),
    ]
