# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20170916_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Hour',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Minute',
            new_name='minute',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Second',
            new_name='second',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='Year',
            new_name='year',
        ),
    ]
