# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_match_게임명'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='which_video',
            field=models.TextField(default='#'),
        ),
    ]
