# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20170917_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='which_chat',
            field=models.TextField(default=''),
        ),
    ]
