# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_livematch_which_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematch',
            name='which_chat',
            field=models.TextField(blank=True, default=''),
        ),
    ]
