# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_test',
            name='abcd',
            field=models.CharField(default='', max_length=15),
        ),
    ]
