# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_id_test_abcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_word', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Id_test',
        ),
    ]
